<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2024/blob/main/Lab01/GS-Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = '5'
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [5]:
a_list = [1, 2, 2, 3.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{'5', 1, 2, 3.0}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [10]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [11]:
%pip install numpy

In [12]:
%pip install timed-decorator

In [13]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [14]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([-2.92465367,  1.50759606, -5.14991639,  4.23413968,  1.37215904,
        3.79694847,  5.36433436,  0.56134292,  4.40147179, -3.87773789,
        2.36393967, -1.08558959, -1.29947992,  4.0523888 , -5.21689645,
        1.5899667 , -1.41131612, -3.41605362,  4.81038723,  3.37645217,
        3.91914075, -4.32722127, -4.49518019,  5.24820089, -2.16359939,
        4.55065239, -3.91656247,  3.11777147, -1.74905479, -4.92363452,
        0.5641108 ,  5.44585604,  1.76571993, -4.02190561, -3.35994233,
        2.22149682,  4.09812071, -5.31378155,  3.09220168,  0.82222951,
       -2.97023823,  3.97970516,  4.94502425,  4.66218484, -3.03010706,
        1.60183493, -2.73897351,  2.21758158, -3.26180894, -4.48488403])

In [15]:
x > 0

array([False,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True,  True,  True, False, False,  True, False,  True, False,
        True, False, False,  True,  True,  True, False, False,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False, False])

In [16]:
x[x > 0]

array([1.50759606, 4.23413968, 1.37215904, 3.79694847, 5.36433436,
       0.56134292, 4.40147179, 2.36393967, 4.0523888 , 1.5899667 ,
       4.81038723, 3.37645217, 3.91914075, 5.24820089, 4.55065239,
       3.11777147, 0.5641108 , 5.44585604, 1.76571993, 2.22149682,
       4.09812071, 3.09220168, 0.82222951, 3.97970516, 4.94502425,
       4.66218484, 1.60183493, 2.21758158])

In [17]:
list(x)

[-2.924653665887048,
 1.5075960640568429,
 -5.149916390687454,
 4.2341396796571935,
 1.3721590394515717,
 3.796948474671476,
 5.364334362985888,
 0.561342917774005,
 4.401471791646525,
 -3.8777378927161608,
 2.3639396682059175,
 -1.0855895873868473,
 -1.299479919487931,
 4.05238880318778,
 -5.216896449087105,
 1.5899666960427536,
 -1.411316115565354,
 -3.41605362170798,
 4.810387225154631,
 3.376452171294357,
 3.9191407517454735,
 -4.327221272786474,
 -4.495180188442527,
 5.248200889135221,
 -2.163599392250142,
 4.550652389636829,
 -3.91656246982821,
 3.117771470345952,
 -1.7490547945145223,
 -4.923634517736714,
 0.5641107961583476,
 5.4458560384669035,
 1.7657199339658423,
 -4.021905608137719,
 -3.3599423341662056,
 2.221496818249026,
 4.0981207053360365,
 -5.313781547381977,
 3.0922016770559964,
 0.8222295063923646,
 -2.970238234152717,
 3.979705157808638,
 4.945024249828052,
 4.662184836712182,
 -3.030107058773623,
 1.601834928741706,
 -2.738973511605792,
 2.217581577172874,
 -3.261

## Comparing numpy arrays to python lists

In [18]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.002762404s
normalize_py(list(float64)[50000]) -> total time: 0.030542745s


#### Python is slower than numpy in general

In [19]:
%%timeit

np.min(x)

30.8 µs ± 4.14 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit

min(y)

2.43 ms ± 184 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [22]:
%%timeit

np.min(a)

4.46 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit

min(b)

1.49 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [24]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [25]:
x = np.random.rand(100, 200)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(100, 200)) -> total time: 0.001544358s
normalize_np_(ndarray(100, 200)) -> total time: 0.003900767s
