<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2024/blob/main/Lab06/BasicTensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
%pip install timed-decorator

In [ ]:
from timed_decorator.simple_timed import timed

# Tensor

## Tensor Creation

In [ ]:
# From Python lists:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [ ]:
# Random tensor with a given size
torch.rand((4, 8))

tensor([[0.0062, 0.8981, 0.3870, 0.7135, 0.7470, 0.2951, 0.9373, 0.0359],
        [0.2583, 0.0901, 0.5022, 0.2888, 0.5995, 0.9775, 0.0333, 0.0576],
        [0.9033, 0.4147, 0.9031, 0.8718, 0.0782, 0.6576, 0.6901, 0.9179],
        [0.2559, 0.7821, 0.2671, 0.0670, 0.7204, 0.0363, 0.4421, 0.7920]])

In [ ]:
# Zero tensor
torch.zeros((3, 3, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.arange(5, 15, 2)

tensor([ 5,  7,  9, 11, 13])

In [ ]:
torch.full((2, 10), 5)

tensor([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Operations with Tensors

In [ ]:
t1 = torch.rand((100, 20, 30))
t2 = torch.rand((100, 20, 30))
print(t1.shape, t2.shape)

torch.Size([100, 20, 30]) torch.Size([100, 20, 30])


In [ ]:
print((t1 * t2).shape)
torch.equal(t1 * t2, torch.mul(t1, t2))

torch.Size([100, 20, 30])


True

In [ ]:
t2t = t2.transpose(1, 2)
print(t2t.shape)
print((t1 @ t2t).shape)

torch.Size([100, 30, 20])
torch.Size([100, 20, 20])


In [ ]:
torch.equal(t1 @ t2t, torch.bmm(t1, t2t))

True

In [ ]:
torch.equal(t1 @ t2t, torch.matmul(t1, t2t))

True

## Casting tensors to device

In [ ]:
# Tensors are by default on CPU
# Please ensure that you have access to a GPU first (in Google Colab, change Runtime type to T4 GPU).
x = torch.arange(5, 15, 2)
x_cuda = x.to('cuda')

In [ ]:
x_cuda

tensor([ 5,  7,  9, 11, 13], device='cuda:0')

In [ ]:
# Tensors should be on the same device
x_cuda + x

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
@timed(show_args=True, use_seconds=True)
def tensor_operations(a, b):
    c = (a * b) @ b.transpose(1, 2)
    c.mean(axis=1)

In [ ]:
torch.manual_seed(10)
a = torch.rand((10000, 200, 300))
b = torch.rand((10000, 200, 300))
a_cuda = a.to('cuda')
b_cuda = b.to('cuda')
print("a", a.shape)
print("b", b.shape)
print("b transposed", b.transpose(1, 2).shape)

a torch.Size([10000, 200, 300])
b torch.Size([10000, 200, 300])
b transposed torch.Size([10000, 300, 200])


In [ ]:
tensor_operations(a, b)

tensor_operations(CpuTensor[10000, 200, 300], CpuTensor[10000, 200, 300]) -> total time: 6.587385930s


In [ ]:
tensor_operations(a_cuda, b_cuda)

tensor_operations(CudaTensor[10000, 200, 300], CudaTensor[10000, 200, 300]) -> total time: 0.177658058s


## Tensor reshaping

In [ ]:
a = torch.rand((100, 20, 25))
print("a", a.shape, sep="\t\t\t")
print("a.flatten()", a.flatten().shape, sep="\t\t")
print("a.reshape(-1)", a.reshape(-1).shape, sep="\t\t")
print("a.reshape(100, -1)", a.reshape(100, -1).shape, sep="\t")
print("a.reshape(100, 25, 20)", a.reshape(100, 25, 20).shape, sep="\t")
print("a.view(-1, 5, 5)", a.view(-1, 5, 5).shape, sep="\t")
print("a.unsqueeze(0)", a.unsqueeze(0).shape, sep="\t\t")
print("a.unsqueeze(-1)", a.unsqueeze(-1).shape, sep="\t\t")

b = torch.tensor([[[1, 2]]])
print("b", b.shape, sep="\t\t\t")
print("b.squeeze()", b.squeeze().shape, sep="\t\t")

a			torch.Size([100, 20, 25])
a.flatten()		torch.Size([50000])
a.reshape(-1)		torch.Size([50000])
a.reshape(100, -1)	torch.Size([100, 500])
a.reshape(100, 25, 20)	torch.Size([100, 25, 20])
a.view(-1, 5, 5)	torch.Size([2000, 5, 5])
a.unsqueeze(0)		torch.Size([1, 100, 20, 25])
a.unsqueeze(-1)		torch.Size([100, 20, 25, 1])
b			torch.Size([1, 1, 2])
b.squeeze()		torch.Size([2])


## Tensor concatenation and stacking

In [ ]:
x = torch.ones((2, 4))
y = torch.zeros((2, 4))

In [ ]:
torch.cat((x, y))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
aux = torch.stack((x, y))
aux

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
aux.shape

torch.Size([2, 2, 4])

## More Tensor operations

In [ ]:
a = torch.rand((5, 20))
a.mean()

tensor(0.5495)

In [ ]:
a.mean(axis=1)

tensor([0.4700, 0.4974, 0.5971, 0.6747, 0.5083])

In [ ]:
a.mean(axis=0)

tensor([0.4852, 0.5720, 0.5703, 0.6602, 0.5591, 0.5038, 0.4658, 0.5259, 0.6198,
        0.3775, 0.5402, 0.4464, 0.6521, 0.4840, 0.5222, 0.6759, 0.5103, 0.7811,
        0.6559, 0.3821])

In [ ]:
a.mean(axis=0).clip(min=0.45, max=0.55)

tensor([0.4852, 0.5500, 0.5500, 0.5500, 0.5500, 0.5038, 0.4658, 0.5259, 0.5500,
        0.4500, 0.5402, 0.4500, 0.5500, 0.4840, 0.5222, 0.5500, 0.5103, 0.5500,
        0.5500, 0.4500])

In [ ]:
a.norm()

tensor(6.1479)

In [ ]:
a[0]

tensor([0.4900, 0.3482, 0.8949, 0.8758, 0.5319, 0.6167, 0.8539, 0.2948, 0.3002,
        0.5883, 0.0181, 0.4062, 0.1126, 0.5991, 0.2320, 0.5963, 0.1228, 0.9220,
        0.5026, 0.0936])

In [ ]:
a[0, 2]

tensor(0.8949)

In [ ]:
a[[0, 2]]

tensor([[0.4900, 0.3482, 0.8949, 0.8758, 0.5319, 0.6167, 0.8539, 0.2948, 0.3002,
         0.5883, 0.0181, 0.4062, 0.1126, 0.5991, 0.2320, 0.5963, 0.1228, 0.9220,
         0.5026, 0.0936],
        [0.5489, 0.5154, 0.3623, 0.8877, 0.4064, 0.5364, 0.4161, 0.9100, 0.0068,
         0.5399, 0.7196, 0.3776, 0.8962, 0.4249, 0.7989, 0.8944, 0.5066, 0.9353,
         0.7374, 0.5219]])

In [ ]:
a[[True, False, True, False, False]]

tensor([[0.4900, 0.3482, 0.8949, 0.8758, 0.5319, 0.6167, 0.8539, 0.2948, 0.3002,
         0.5883, 0.0181, 0.4062, 0.1126, 0.5991, 0.2320, 0.5963, 0.1228, 0.9220,
         0.5026, 0.0936],
        [0.5489, 0.5154, 0.3623, 0.8877, 0.4064, 0.5364, 0.4161, 0.9100, 0.0068,
         0.5399, 0.7196, 0.3776, 0.8962, 0.4249, 0.7989, 0.8944, 0.5066, 0.9353,
         0.7374, 0.5219]])

In [ ]:
mask = a > 0.5
mask

tensor([[False, False,  True,  True,  True,  True,  True, False, False,  True,
         False, False, False,  True, False,  True, False,  True,  True, False],
        [ True,  True, False, False, False, False, False,  True,  True, False,
          True, False,  True,  True, False, False, False, False, False, False],
        [ True,  True, False,  True, False,  True, False,  True, False,  True,
          True, False,  True, False,  True,  True,  True,  True,  True,  True],
        [False,  True,  True,  True,  True,  True, False,  True,  True, False,
         False, False,  True,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True, False,  True, False,  True, False,
          True,  True,  True, False, False,  True,  True,  True,  True, False]])

In [ ]:
mask[0]

tensor([False, False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False,  True, False,  True, False,  True,  True, False])

In [ ]:
indices = mask[0].nonzero()
indices

tensor([[ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 9],
        [13],
        [15],
        [17],
        [18]])

In [ ]:
mask[0][indices]

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])

In [ ]:
mask.all(axis=0)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False])

In [ ]:
mask.any(axis=1)

tensor([True, True, True, True, True])

In [ ]:
b = a[mask]
b

tensor([0.8949, 0.8758, 0.5319, 0.6167, 0.8539, 0.5883, 0.5991, 0.5963, 0.9220,
        0.5026, 0.9129, 0.9999, 0.7076, 0.9577, 0.9390, 0.6820, 0.5600, 0.5489,
        0.5154, 0.8877, 0.5364, 0.9100, 0.5399, 0.7196, 0.8962, 0.7989, 0.8944,
        0.5066, 0.9353, 0.7374, 0.5219, 0.8840, 0.8011, 0.8149, 0.8111, 0.6555,
        0.5756, 0.9960, 0.7453, 0.6844, 0.9748, 0.8623, 0.9068, 0.7244, 0.9733,
        0.7085, 0.8408, 0.5933, 0.8381, 0.6212, 0.5382, 0.8246, 0.8299, 0.5475,
        0.9760, 0.9097])

In [ ]:
b[b < 0.7] = 0
b

tensor([0.8949, 0.8758, 0.0000, 0.0000, 0.8539, 0.0000, 0.0000, 0.0000, 0.9220,
        0.0000, 0.9129, 0.9999, 0.7076, 0.9577, 0.9390, 0.0000, 0.0000, 0.0000,
        0.0000, 0.8877, 0.0000, 0.9100, 0.0000, 0.7196, 0.8962, 0.7989, 0.8944,
        0.0000, 0.9353, 0.7374, 0.0000, 0.8840, 0.8011, 0.8149, 0.8111, 0.0000,
        0.0000, 0.9960, 0.7453, 0.0000, 0.9748, 0.8623, 0.9068, 0.7244, 0.9733,
        0.7085, 0.8408, 0.0000, 0.8381, 0.0000, 0.0000, 0.8246, 0.8299, 0.0000,
        0.9760, 0.9097])